general:
  time_zone: Europe/Berlin
  SEV-lines use normal line icon colors: False
  QR-Code-content: https://github.com/Irgendwer008/OpenDepartureDisplay
  QR-Code-height: 0.9
windows:
  - station: Durlacher Tor / KIT-Campus Süd
    position_x: 0
    position_y: 0
    width: 800
    height: 400
  - station: Kronenplatz
    position_x: 800
    position_y: 0
    width: 600
    height: 300
  - station: Hauptbahnhof
    position_x: 1920
    position_y: 0
    width: 1920
    height: 1080
# Here is one example list i found to quickly search for stop points and their refs: https://github.com/ZeroTwoWeeb/MMM-KVV-Trias/blob/main/stops.txt
stations:
  Durlacher Tor / KIT-Campus Süd:
    - stop_point_ref: de:08212:3
      prefix: ""
      suffix: ""
    - stop_point_ref: de:08212:1001
      prefix: ""
      suffix: "(U)"
  Kronenplatz:
    - stop_point_ref: de:08212:80
    - stop_point_ref: de:08212:1002
      suffix: "(U)"
  Hauptbahnhof:
    - stop_point_ref: de:08212:88
      suffix: "(S)"
    - stop_point_ref: de:08212:90
      suffix: "(Hbf)"
    - stop_point_ref: de:08212:89
      suffix: "(N)"
colors:
  header_background: "#FFA500"
  header_text: "#000000"
  departure_entry_lighter: "#FFFFFF"
  departure_entry_darker: "#EEEEEE"
  departure_entry_text: "#000000"
  default_icon_background: "#006EFF"
  default_icon_text: "#FFFFFF"
  qr_code_background: "#FFFFFF"
  qr_code_foregreound: "#000000"
credentials:
  url: https://projekte.kvv-efa.de/YOUR-URL/trias
  requestor_ref:  YOUR-REQUESTOR_REF